services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=dentallocum'
      - 'MYSQL_PASSWORD=Ma1ya@nk3'
      - 'MYSQL_ROOT_PASSWORD=Ma1ya@nk3'
      - 'MYSQL_USER=root'
    ports:
      - '3306'
